#!/bin/bash

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📖 掌上时光机 · 命令手册"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔹 备份"
echo "   命令：备份"
echo "   作用：备份三库（图文笔记 / 图文相册 / 主博客主页）"
echo "   特点："
echo "     • 文件名带时间戳（年月日_时分）"
echo "     • 自动清理 7 天前的旧备份"
echo "     • 备份位置：手机内部存储 /sdcard/"
echo ""
echo "🔹 恢复"
echo "   命令：恢复"
echo "   作用：按时间恢复三库"
echo "   特点："
echo "     • 手动输入时间标识（如 20260629_0909）"
echo "     • 恢复前自动备份当前数据"
echo "     • 缺库自动跳过，不报错"
echo ""
echo "🔹 清理（手动）"
echo "   命令：无（内置于备份）"
echo "   作用：仅删除 7 天前的备份 zip"
echo "   手动预览："
echo "     find /sdcard/ -maxdepth 1 -name \"*笔记*.zip\" -mtime +7 -print"
echo "   手动执行："
echo "     find /sdcard/ -maxdepth 1 -name \"*.zip\" -mtime +7 -delete"
echo ""
echo "🔹 查看备份文件"
echo "   命令："
echo "     ls -lh /sdcard/*笔记*.zip"
echo "     ls -lh /sdcard/*相册*.zip"
echo "     ls -lh /sdcard/*主页*.zip"
echo ""
echo "🔹 查看命令来源"
echo "   命令："
echo "     alias          # 查看所有中文命令"
echo "     type 备份      # 查看备份指向"
echo "     type 恢复"
echo "     nano ~/backup-all.sh   # 查看备份脚本"
echo "     nano ~/restore-all.sh  # 查看恢复脚本"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 提示：所有命令均在 Termux 中执行"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
